# Generated by Django 4.0 on 2021-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=1)),
                ('team0', models.CharField(max_length=1)),
                ('team1', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('winner', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
